### ISSUE TITLE
Correct alignment to `BH.oM.Structure.Elements.Bar`'s `Start` and `End` renamings in `string` checks

### ISSUE THREAD

**Issue by alelom** [BHoM/DiffingTests_Prototypes#15]
0ecfd6021a3ec3759ea316d9fef848fbff020c76 aligned the references to the new names done in https://github.com/BHoM/BHoM/pull/1579, but missed to update all checks that reference the names of such properties. We have 4 failing tests at the moment.

@FraserGreenroyd FYI

**Comment by FraserGreenroyd** [comment]
🙈
